# Generated by Django 5.0.1 on 2024-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0002_reserva_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_secretaria',
            field=models.BooleanField(default=True),
        ),
    ]
