# Generated by Django 5.0.1 on 2024-03-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armois.especialidad'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
