# Generated by Django 5.0.1 on 2024-08-05 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
