# Generated by Django 5.0.1 on 2024-08-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0002_profesional_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatencion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
