# Generated by Django 5.0.1 on 2024-03-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0003_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subespecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subespecialidades', to='armois.especialidad')),
            ],
        ),
    ]
