# Generated by Django 5.0.1 on 2024-08-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0003_horarioatencion_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioatencion',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
