# Generated by Django 5.0.1 on 2024-08-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0004_rename_is_active_horarioatencion_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_synced_with_google_calendar', models.BooleanField(default=False)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armois.horarioatencion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armois.paciente')),
            ],
        ),
    ]
