# Generated by Django 5.0.1 on 2024-08-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0006_paciente_direccion_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='google_calendar_event_id',
        ),
    ]
