# Generated by Django 5.0.1 on 2024-04-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0007_horariodisponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorarioDisponible',
        ),
    ]
