# Generated by Django 5.0.1 on 2024-08-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0008_reserva_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armois.especialidad'),
        ),
    ]
