# Generated by Django 5.0.1 on 2024-08-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0009_reserva_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armois.especialidad'),
        ),
    ]
