# Generated by Django 5.0.1 on 2024-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0009_horarioatencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatencion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
