# Generated by Django 5.0.1 on 2024-04-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armois', '0010_alter_horarioatencion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioatencion',
            name='dia_semana',
        ),
    ]
